### PR TITLE
Revert last merge

### PR DESCRIPTION
**Pull request by szszszsz**
Revert last merge

@Niklas-Nitrokey : Could you check, is this the expected result? I have reverted the merge commit to initial state, and applied your changes from the second commit you have sent.

### CODE REVIEW

**Comment by szszszsz** [comment]
Used command:
```
git revert -m 2 HEAD
```

The `-m` switch chooses which branch one would like to revert to from the merge. The HEAD means currently checked out commit, which in this case accidentally points on the merge commit (otherwise the commit hash has to be used).
The other changes from your branch were cherry picked, but only one commit. The one with factory reset update seemed to be already applied by someone else.

**Comment by Niklas-Nitrokey** [comment]
yes, that's it! thank you very much :)

**Comment by szszszsz** [comment]
Alright!
The CI fails though. Could you check it and whether does it render correctly locally on your side?

**Comment by szszszsz** [comment]
@Niklas-Nitrokey I think you have added the required changes already to master. Please confirm, so I could close this PR.

**Comment by Niklas-Nitrokey** [comment]
yes, i added them already.

**Comment by szszszsz** [comment]
Closing as done.

**Pull request closed without merging**
