### PR TITLE
Update administration.rst: wrong verb

### PR DESCRIPTION
**Pull request by jpmens**
s/set/get/

### CODE REVIEW

**Comment by jans23** [comment]
Thank you for your contribution. Please point it to branch "main".

**Comment by jpmens** [comment]
I'm not sure I know how to do that; I clicked on "Edit this page" in the docs and was taken to the Nitrokey documentation repo.

**Comment by jpmens** [comment]
rabbit-11467

**Comment by jpmens** [comment]
rabbit-11468

I give up. 404 on your end.

**Comment by jans23** [comment]
Nevermind. I fixed it in 907de7d9b0bbffadf78144babd42bfb16ed4bfef

**Pull request closed without merging**
