### PR TITLE
Add scaffolding for nitropy documentation

### PR DESCRIPTION
**Pull request by robin-nitrokey**

### CODE REVIEW

**Comment by szszszsz** [comment]
Bump

**Comment by daringer** [comment]
yeah that's on me, increasing priority ;) will do it tomorrow(tm)

**Comment by daringer** [comment]
Sooo, yeah looks very good, I love it, two points:
1) consistent naming (so let's stick the executable `nitropy` first), especially relevant for the articles linking into `software/nitropy`
2) like the sub-articles shown in `software`, but here we need consistency, too either have this like that everywhere or nowhere

In order to merge: 1) can be easily done by grepping for pynitrokey I guess and 2) is just adding `max-depth: 2` everywhere
then we just merge, wait for some feedback for 2) and keep or remove it afterwards...

**Comment by jans23** [comment]
IMO consistent naming would be `pynitrokey` because that's used in other places of the documentation already and it' the name of the software.

**Comment by szszszsz** [comment]
Agreed. We had that decision back then and have to stick now. `pynitrokey` is the name, and `nitropy` is the tool's call. This should be documented too to clear the doubts.
Briefly looking, these pages look good enough. Let's merge it!

**Comment by robin-nitrokey** [comment]
@jans23 

> IMO consistent naming would be `pynitrokey` because that's used in other places of the documentation already and it' the name of the software.

@szszszsz 
> Agreed. We had that decision back then and have to stick now. `pynitrokey` is the name, and `nitropy` is the tool's call. This should be documented too to clear the doubts. Briefly looking, these pages look good enough. Let's merge it!

I discussed the naming topic with @daringer last week and we had a different understanding:  `pynitrokey` is only the name for the package and not relevant for the user, `nitropy` (or: `nitrokey-tool` in the future) is the actual application.  We even discussed whether we should go forward with the renaming before publishing this.  (Also, the [NetHSM](https://docs.nitrokey.com/nethsm/cli.html) and [Nitrokey 3](https://docs.nitrokey.com/nitrokey3/linux/nitropy.html) documentation already uses the name `nitropy`.)  Should I rename `nitropy` to `pynitrokey` in the docs anyway?

**Comment by jans23** [comment]
> Should I rename nitropy to pynitrokey in the docs anyway?

No opinion. Renaming would be most appreciated.

**Comment by daringer** [comment]
> @daringer Can you please elaborate on that? Is this about the navigation bar or the list in the page body? And what is the expected output?

If I navigate into "Software" -> "nitropy" I can see a toc with the depth 2, instead of depth 1 (as it is everywhere else, e.g. nextbox). So "software" -> "nitropy" looks like this:
* [All Platforms](https://github.com/Nitrokey/nitrokey-documentation/pull/all-platforms/index.html)  `depth 1`
   * [Installing nitropy with pipx](https://github.com/Nitrokey/nitrokey-documentation/pull/all-platforms/installation.html) `depth 2`
 * [Windows](https://github.com/Nitrokey/nitrokey-documentation/pull/windows/index.html)
   * [Installing nitropy on Windows](https://github.com/Nitrokey/nitrokey-documentation/pull/windows/installation.html)
 * [Linux](https://github.com/Nitrokey/nitrokey-documentation/pull/linux/index.html)
   * [Setting up the udev rules for nitropy](https://github.com/Nitrokey/nitrokey-documentation/pull/linux/udev.html)

and e.g. NextBox looks like this (even though there are depth 2 items):

* [Getting Started](https://github.com/Nitrokey/nitrokey-documentation/pull/gettingstarted.html)
* [Hardware Overview](https://github.com/Nitrokey/nitrokey-documentation/pull/hardware-overview.html)
* [Connect Devices](https://github.com/Nitrokey/nitrokey-documentation/pull/clients/index.html)
* [Backup and Restore](https://github.com/Nitrokey/nitrokey-documentation/pull/backup-restore.html)
* [Managing Remote Access](https://github.com/Nitrokey/nitrokey-documentation/pull/remote/index.html)
* [Technical Documentation](https://github.com/Nitrokey/nitrokey-documentation/pull/technical/index.html)
* [NextBox FAQ](https://github.com/Nitrokey/nitrokey-documentation/pull/faq/index.html)

actually I like the `max-depth: 2` approach a little more - whichever we choose it should be consistent.

**Comment by szszszsz** [comment]
Bumping

**Comment by jans23** [comment]
I agree to the above reasoning and think "nitropy" is the most appropriate name as of now (which will be renamed in the future).

Can this be merged?

**Comment by jans23** [comment]
Title words should start with capital letters.

**Comment by szszszsz** [comment]
Let's merge it and clean up later (by adding another ticket / PR). It's better to have an imperfect description, than having none.

**Pull request merged**
