### PR TITLE
Update nitrokey 3 OpenPGP to add installation procedure and factory reset

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**

### CODE REVIEW

**Comment by jans23** [comment]
Shouldn't we locate openpgp.rst and reset.rst at /shared/ instead of /nitrokey3/shared/ ?

I assume you copied content from another file to /nitrokey3/shared/openpgp.rst Wouldn't it be better to share and include the file instead of copying the content?

**Comment by sosthene-nitrokey** [comment]
The reset is specific to the Nitrokey 3, so I don't see why it should be shared with the rest, even though I did copy some text from the fido2 reset instructions.
The OpenPGP one is modified to add the header containing instruction to use a firmware release more recent than 1.4.0,  and to call it "Nitrokey 3" instead of just "Nitrokey"

**Comment by sosthene-nitrokey** [comment]
The note to upgrade to 1.4.0 doesn't make sense for other devices

**Comment by jans23** [comment]
> The note to upgrade to 1.4.0 doesn't make sense for other devices

Yes, that's why I suggest to separate this product-specific note and combine it with a generalized openpgp.rst via "include" statements.

**Comment by sosthene-nitrokey** [comment]
Ok, I'll do that.

**Review by jans23 — APPROVED** [review]

**Pull request merged**
